# Generated by Django 5.2.8 on 2025-11-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
